[book]
authors = ["Matěj Frič"]
language = "en"
multilingual = false
src = "src"
title = "Notitia Nexus"

[preprocessor.katex]
after = ["links"]

[output.html.fold]
enable = true
level = 0

[output.html]
git-repository-url = "https://github.com/matejfric/mdbook"
default-theme = "coal"
preferred-dark-theme = "coal"
