[book]
authors = ["Matěj Frič"]
language = "en"
multilingual = false
src = "src"
title = "Notitia Nexus"

[preprocessor.katex]
after = ["links"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.fold]
enable = true
level = 0

[output.html]
git-repository-url = "https://github.com/matejfric/mdbook"
additional-css = ["src/custom.css"]
additional-js = ["src/custom.js", "src/mermaid.min.js", "src/mermaid.init.js"]
default-theme = "coal"
preferred-dark-theme = "coal"
